package com;

public enum RateListNameEnum {
	CONSULTATION,
    CONSULTATION_OPD,
    CONSULTATION_FOR_INPATIENTS,
    DRESSINGS_OF_WOUNDS,
    ASPIRATION_PLURAL_EFFUSION_DIAGNOSTIC,
    FREE_FOLLOW_UP,
    OPD_CHARGE
}
